trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-pipelines.yaml
    exclude:
    - Readme.md

resources:
- repo: self

variables:
  IMAGE_NAME: houssemdocker/album-backend-api
  CONTAINERAPPS_APP: album-backend-api
  CONTAINERAPPS_ENVIRONMENT: aca-environment
  RESOURCE_GROUP: rg-containerapps-azure-pipelines
  TAG: '$(Build.BuildId)'
  system.debug: true
  DOCKER_USERNAME: $(dockerUsername)
  DOCKER_PASSWORD: $(dockerPassword)
  dockerRegistryServiceConnection: '6e118ffb-d3c9-44bf-8bbc-ed8510f64d2f'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build
  displayName: 'Build Project'

- task: Docker@2
  inputs:
    command: 'build'
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'houssemdocker/album-backend-api'

- script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
  displayName: 'Docker Login'

- script: cat /home/vsts/work/_temp/DockerConfig_1723927431423/config.json
  displayName: 'Inspect Docker Config'

- task: Docker@2
  inputs:
    command: 'push'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'houssemdocker/album-backend-api'
    tags: |
      $(Build.BuildId)

